### ISSUE TITLE
Consider redesigning our information files

### ISSUE THREAD

**Issue by travs** [melonproject/smart-contracts#318]
Currently we use several files in `utils/info/*`.

It may be worth reconsidering how we store and read this information, for example to reduce any potential duplication of information within or between files.

**Comment by schmidsi** [comment]
Generally, I prefer to read info like this directly from the blockchain if possible. As I understand these files, they are a workaround for information that is not possible anymore to retrieve from the blockchain (right?)

So as a rule of thumb we could say: If info can be retrieved from the blockchain then there is no need for a hard coded file.

In detail I'd say: We can remove exchangeInfo.js and priceFeedInfo.js because these addresses are already in addressBook.json.

**Comment by schmidsi** [comment]
Another idea: As I understand the registered assets on a PriceFeed (which inherits from AssetRegistrar) are in this `mapping (address => Asset) public information;`. There is no built in function to get a list of all assets out of this mapping? (This sounds a bit weird to me since all info on the blockchain is public but I'm told it is not possible). But we could reduce a list of all possible asset addresses e.g. `const allAssets = ['0xdead...beef', '0xbad...a55', ...]` through this mapping function into a collection of registered assets like:

```javascript
const registeredAssets = allAssets
   .map(assetAddress =>priceFeedContract.instance.information.call(assetAddress))
   .filter(information => !!information)
```

This way we would only need to provide one (curated white-) list of asset addresses for each network and melon.js can build the rest of the information by itself.

**Comment by jennazenk** [comment]
> There is no built in function to get a list of all assets out of this mapping? (This sounds a bit weird to me since all info on the blockchain is public but I'm told it is not possible). 

it's linked to this issue raised during audit: https://github.com/melonproject/protocol/issues/233

**Comment by schmidsi** [comment]
Thanks for the link. I understand the security aspect but it doesn't explain why it is not possible to somewhere have a function on the AssetRegistrar named `getAllAssets` or on the fund.

I mean there must be a place to get all assets and loop over it to calculate GAV, NAV, etc. Can we expose it?

**Comment by schmidsi** [comment]
So we implemented this polling like described above: https://github.com/melonproject/melon.js/blob/94d96f408d4c439ef7a8b5e5f3e1a4ce5cce611a/lib/assets/utils/getWhiteListedAssets.js

Other than this list of assets, we only need this addresses per chain:

complianceAddress
exchangeAdapterAddress
exchangeAddress
nativeAssetSymbol
priceFeedAddress
quoteAssetSymbol
rankingAddress
riskManagementAddress
versionAddress

Would be cool to have it in exactly this form. I.e. not "RMMakeOrders" but "riskManagementAddress"

**Comment by travs** [comment]
> I mean there must be a place to get all assets and loop over it to calculate GAV, NAV, etc. Can we expose it?

Agree. We have raised #407 which covers this I believe.

> In detail I'd say: We can remove exchangeInfo.js and priceFeedInfo.js because these addresses are already in addressBook.json.

Yes, can remove pricefeedInfo I think, since we are going with this canonical pricefeed idea.

The way it is now is that addressBook.json is a deployment artifact, so contracts we deploy go in there. Maybe it makes sense to keep exchangeInfo.js for this reason (we don't deploy OasisDex for instance).

Have sent you a message about the last point to clarify.
